### ISSUE TITLE
学习vm-cluster过程中碰到的一些问题

### ISSUE THREAD

**Issue by wangkuiyi** [k8sp/vm-cluster#4]
从这个工作里学到了好多Vagrantfile的用法。多谢郑波 @zhengbo0 ！！

有几个问题，想确认一下我的想法：
1. 从 [Vagrantfile:L3](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L3) 到 [Vagrantfile:L6](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L6) 这几行是不是对master VM和worker VM无效（因为他俩没有操作系统），所以其实可以挪到 [Vagrantfile:L9](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L9) 之后定义 `bs`的代码段里？
2. [Vagrantfile:L5](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L5) 这里为什么需要把 `k8s.baifendian.com`加入到`/etc/resolv.conf`里呢？希望是不一定需要的？
3. 在 [Vagrantfile:L11](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L11) 里用到两个变量 `$update_channel`和`image_version`。没看到这两个变量的定义在哪儿呢？
4. `install_bootstrapper.sh`是不是改名叫`provision_bootstrapper_vm.sh`意思更准确一点？
5. [Vagrantfile:L41](https://github.com/k8sp/vm-cluster/blob/master/Vagrantfile#L41)里，`wk.customize [ ..."--macaddress1", "auto"]` 这段是说每次vagrant up worker的时候，其mac地址都会变化吗？我注意到我们引以为参考的这篇[帖子](http://www.jedi.be/blog/2011/11/04/vagrant-virtualbox-hostonly-pxe-vlans/)里这么写了，但是一直没有搞明白为什么要写这个。
6. [intall_bootstrapper.sh:L9](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L9) 这里的 `cd ~` 是不是就是 `cd /root` 了？我看[install_bootstrapper.sh:L14](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L14) 这里有 `mkdir -p /root...`。
7. 什么时候bootstrapper会需要（免密码）登录其他机器呢？我看到[install_bootstrapper.sh:L37](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L37)这里实现了这个功能。
8. [install_bootstrapper.sh:L47](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L47) 这里为什么需要删除`./bsroot.sh`生成的TLS assets，并且重新生成一遍呢？
9. [install_bootstrapper.sh:L60](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L60) 这里的修改是不是应该在 https://github.com/k8sp/sextant/ 里修改？
10. 类似的，[install_bootstrapper.sh:L64](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L64) 这里的修改是不是也应该放到 https://github.com/k8sp/sextant/ 里？
11. [install_bootstrapper.sh:L29](https://github.com/k8sp/vm-cluster/blob/master/install_bootstrapper.sh#L29)没有在master VM上部署Ceph monitor是因为 https://github.com/k8sp/sextant/ 还没有支持 Ceph吧？

**Comment by zhengbo0** [comment]
问题1：那个配置是针对所有虚拟机的配置，master VM和worker也会有效
问题2：和旭哥沟通后，得到答案是 `为了在bootstrapper上能通过dns找到其他的主机`

---

By Yi: 如果在百分点公司之外运行这个Vagrantfile，这一行加 k8s.baifendian.com到/etc/resolv.conf 是不是就无效了？

---

问题3：待修改，需要在脚本中指定

```
$update_channel = "alpha"
$image_version = "current"
```

问题4：待修改
问题5：之前和青松沟通时，青松反馈是：`用以解决如果启动两个worker的时候，mac地址一样的问题`，目前我还没有遇到他说的这个问题，为了避免踩坑，提前填坑了
问题6：测试环境默认用的root用户，待修改为确定目录
 `cd /root`
问题7：为了从bootstrapper虚拟机上免密码登陆到其他虚拟机上如master,worker虚拟机，可以指定虚拟机的用户名和密码，待讨论

---

By Yi：哦。为什么需要从bootstrapper VM登录到其他虚拟服务器呢？

---

问题8：可以不删除，如果再次安装时，需要判断证书是否存在，这里偷了一个懒，让所有的证书重新生成了

---

哦。如果不删除，下次再安装的时候，再重新走一遍全流程（包括重新生成全部TLS asset）可以吗？

---

问题9：前期测试时，物理机器不存在无法找到pxe server的问题，但是虚拟机环境中会存在，所以没有在sextant项目直接修改

---

要不要物理机环境也测试一下？如果不需要，咱们就删了？

---

问题10：确实需要判断一下docker版本是否一致的问题，这个需要和武哥他们确认一下
问题11：对，虚拟机环境暂时没有对Ceph支持，后期可以把这个加上，待讨论

**Comment by wangkuiyi** [comment]
了解了。还有一些问题。请帮我再看看。多谢!

**Comment by zhengbo0** [comment]
问题2，问题7，问题9，问题10，问题11，麻烦  @wangkuiyi @Yancey1989 @typhoonzero 确认一下

**Comment by zhengbo0** [comment]
`bootstrapper VM登录到其他虚拟服务器` 主要是为了登录到其他虚拟机上面，查看k8s是否正确被安装，并且正常启动。

---

Yi: 明白了。这个是不是应该可以在host上（类似实际环境中的笔记本电脑）上生成ssh key，然后用来登录bootstrapper VM、master VM和worker VM呢？ 

---

他们是内部网络，host主机无法直接访问

**Comment by zhengbo0** [comment]
问题2：这个和cluster-desc里dns的 domain设置有关，在其他地方使用应该不受影响

---

Yi: 如果在vm cluster里不需要 dns.baifendian.com，咱们删掉？

---

问题8：可以不删除，全部重新走一边，重新生成的证书会覆盖以前已经存在的

---

Yi: 那咱们改一下吧？我想尽量不重复bsroot.sh已经做过的工作，这样读者比较容易理解。你看呢？

---

问题9：物理机我没有测试过，@Yancey1989 @typhoonzero 需要确认下，是否有必要删除掉网卡绑定

**Comment by zhengbo0** [comment]
问题2：删掉会导致，在bootstrapper的机器上无法通过dns找到k8s的节点，如果没有这种需求是可以删掉的

---

Yi: 看上去，这个upstream DNS server应该改成一个可以配置的选项？
